version: '3.9'

services:

  # CONFIG SERVER
  config-server:
    image: sid118/config-server:latest
    container_name: config-server
    ports:
      - "8888:8888"
    restart: always

  # EUREKA
  eureka-server:
    image: sid118/eureka-server:latest
    container_name: eureka-server
    depends_on:
      - config-server   # ✅ order maintained
    ports:
      - "8761:8761"
    restart: always

  # AUTH DB
  auth-db:
    image: mysql:8
    container_name: auth-db
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: mediquick_db
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  # CONSULTANT DB
  consultant-db:
    image: mysql:8
    container_name: consultant-db
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: mediquick_consultant_db
    ports:
      - "3308:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  # AUTH SERVICE
  auth-service:
    image: sid118/auth-service:latest
    container_name: auth-service
    depends_on:
      - config-server
      - eureka-server
      - auth-db
    ports:
      - "8081:8081"
    restart: always

  # CONSULTANT SERVICE
  consultant-service:
    image: sid118/consultant-service:latest
    container_name: consultant-service
    depends_on:
      - config-server
      - eureka-server
      - consultant-db
    ports:
      - "8082:8082"
    restart: always

  # API GATEWAY (LAST)
  api-gateway:
    image: sid118/api-gateway:latest
    container_name: api-gateway
    depends_on:
      - config-server
      - eureka-server
      - auth-service
      - consultant-service
    ports:
      - "8091:8091"
    restart: always

  karate-tests:
    image: maven:3.9.9-eclipse-temurin-21
    container_name: karate-tests
    depends_on:
      - api-gateway
    volumes:
      - ./karate-tests:/app
    working_dir: /app
    command: >
      sh -c "
      sleep 20 &&
      mvn test -Dkarate.env=docker
      "