version: '3.9'

services:

  config-server:
    image: sid118/config-server:latest
    container_name: config-server
    ports:
      - "8888:8888"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  eureka-server:
    image: sid118/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      config-server:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-db:
    image: mysql:8
    container_name: auth-db
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: mediquick_db
    ports:
      - "3307:3306"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  consultant-db:
    image: mysql:8
    container_name: consultant-db
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: mediquick_consultant_db
    ports:
      - "3308:3306"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    image: sid118/auth-service:latest
    container_name: auth-service
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      auth-db:
        condition: service_healthy
    ports:
      - "8081:8081"
    restart: always

  consultant-service:
    image: sid118/consultant-service:latest
    container_name: consultant-service
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      consultant-db:
        condition: service_healthy
    ports:
      - "8082:8082"
    restart: always

  api-gateway:
    image: sid118/api-gateway:latest
    container_name: api-gateway
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      auth-service:
        condition: service_started
      consultant-service:
        condition: service_started
    ports:
      - "8091:8091"
    restart: always

networks:
  default:
    name: mediquick_network