server.port=8082
spring.application.name=consultant-service
spring.config.import=optional:configserver:http://config-server:8888

spring.datasource.url=jdbc:mysql://mysql:3306/mediquick_consultant_db
spring.datasource.username=root
spring.datasource.password=root@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=mediquickSecretKeyForJwtGeneration123456