package com.mediquick.auth.entity;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class UserTest {

    private User user;

    @BeforeEach
    void setUp() {
        user = new User("test@gmail.com", "password123", "Test User");
    }

    // ===== CONSTRUCTOR =====

    @Test
    void constructor_SetsFieldsCorrectly() {
        assertEquals("test@gmail.com", user.getEmail());
        assertEquals("password123", user.getPassword());
        assertEquals("Test User", user.getName());
    }

    @Test
    void defaultConstructor_CreatesEmptyUser() {
        User emptyUser = new User();
        assertNull(emptyUser.getEmail());
        assertNull(emptyUser.getPassword());
        assertNull(emptyUser.getName());
    }

    // ===== GETTERS & SETTERS =====

    @Test
    void setEmail_UpdatesEmail() {
        user.setEmail("new@gmail.com");
        assertEquals("new@gmail.com", user.getEmail());
    }

    @Test
    void setPassword_UpdatesPassword() {
        user.setPassword("newPassword");
        assertEquals("newPassword", user.getPassword());
    }

    @Test
    void setName_UpdatesName() {
        user.setName("New Name");
        assertEquals("New Name", user.getName());
    }

    // ===== ID =====

    @Test
    void getId_NewUser_ReturnsNull() {
        // id is auto-generated by DB, so new user has null id
        assertNull(user.getId());
    }
}