server.port=8761
spring.application.name=eureka-server
spring.config.import=optional:configserver:http://config-server:8888

#eureka.client.enabled=false

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
management.endpoints.web.exposure.include=health